
global:
  resolve_timeout: 5m

route:
  receiver: webhook-receiver
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://65.1.134.123:5001/'  # new IP
        send_resolved: true  # Correct indentation here
